name: CI/CD

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true

      - name: Run clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features -- -Dwarnings

  cd:
    runs-on: ubuntu-latest
    needs: ci
    if: "!contains(github.event.head_commit.message, '[skip ci]') && github.ref == 'refs/heads/master'"
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: Authentication with GCP
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_DEPLOY_CREDENTIALS }}'
          token_format: 'access_token'

      - name: Authenticate with GCR
        uses: 'docker/login-action@v1'
        with:
          registry: 'gcr.io'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: gcr.io/${{ vars.GCP_PROJECT }}/birthday-checker:latest

      - name: Deploy new cloudrun revision
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: '${{ vars.CLOUD_RUN_SERVICE }}'
          image: 'gcr.io/cloudrun/hello'